IgniteUI/igniteui-wc-examples

.gitignore, gulpfile.js
mdd-update-gulpfile-allow-porting
=> mdd-update-gulpfile-allow-porting

gulpfile.js, templates/porting/index.html
=> mdd-update-gulpfile

gulpfile.js, templates/sample/src/index.ts, templates/shared/src/StocksHistory.ts, templates/shared/src/StringUtils.ts, templates/shared/src/WorldCities.ts, templates/shared/src/WorldConnections.ts, templates/shared/src/WorldLocations.ts, templates/shared/src/WorldUtils.ts
=> mdd-individual-samples-done

gulpfile.js
=> mdd-update

samples/charts/doughnut-chart/explosion/index.html, samples/charts/doughnut-chart/explosion/src/DoughnutChartExplosion.ts, samples/charts/doughnut-chart/legend/index.html, samples/charts/doughnut-chart/legend/src/DoughnutChartLegend.ts, samples/charts/doughnut-chart/selection/index.html, samples/charts/doughnut-chart/selection/src/DoughnutChartSelection.ts, samples/charts/pie-chart/explosion/index.html, samples/charts/pie-chart/explosion/src/PieChartExplosion.ts, samples/charts/pie-chart/legend/index.html, samples/charts/pie-chart/legend/src/PieChartLegend.ts, samples/charts/pie-chart/others/index.html, samples/charts/pie-chart/others/src/PieChartOthers.ts, samples/charts/pie-chart/selection/index.html, samples/charts/pie-chart/selection/src/PieChartSelection.ts
SEO samples for WC PieChart and DoughnutChart
=> SEO samples for WC PieChart and DoughnutChart

samples/charts/sparkline/display-lines/index.html, samples/charts/sparkline/display-lines/src/index.ts, samples/charts/sparkline/display-types/index.html, samples/charts/sparkline/display-types/src/index.ts
=> update sparkline data

samples/inputs/form/overview/index.html, samples/inputs/form/overview/src/index.ts
=> fix(form): fixed sample when loading in browser

browser/public/index.html, browser/tasks/gulp-samples.js, samples/layouts/icon/sizing/ReadMe.md, samples/layouts/icon/sizing/index.html, samples/layouts/icon/sizing/package.json, samples/layouts/icon/sizing/sandbox.config.json, samples/layouts/icon/sizing/src/index.css, samples/layouts/icon/sizing/src/index.ts, samples/layouts/icon/sizing/tsconfig.json, samples/layouts/icon/sizing/tslint.json, samples/layouts/icon/sizing/webpack.config.js, samples/layouts/icon/styling/ReadMe.md, samples/layouts/icon/styling/index.html, samples/layouts/icon/styling/package.json, samples/layouts/icon/styling/sandbox.config.json, samples/layouts/icon/styling/src/index.css, samples/layouts/icon/styling/src/index.ts, samples/layouts/icon/styling/tsconfig.json, samples/layouts/icon/styling/tslint.json, samples/layouts/icon/styling/webpack.config.js
=> samples(icon): add icon samples

samples/menus/nav-drawer/add-mini/index.html, samples/menus/nav-drawer/add-mini/package.json, samples/menus/nav-drawer/add-mini/src/index.ts
=> sync mini and nav drawer items

samples/inputs/button/flat/index.html, samples/inputs/button/overview/index.html, samples/inputs/button/size/index.html, samples/inputs/button/styling/src/ButtonStyle.css, samples/inputs/button/styling/src/index.ts
=> fix(button): set flat variant to buttons and change default size

samples/layouts/card/horizontal/package.json, samples/layouts/card/overview/index.html, samples/layouts/card/overview/package.json, samples/layouts/card/semi-horizontal/package.json, samples/layouts/card/styling/package.json, samples/layouts/card/styling/src/CardStyling.css
=> fix card live editing and styling

samples/menus/nav-bar/overview/src/index.ts
=> fix(navbar): defineComponents icon

samples/inputs/ripple/button/index.html, samples/inputs/ripple/color/index.html
=> add container with margin on ripple samples

samples/inputs/form/overview/index.html
=> sample(form): remove novalidate

samples/menus/nav-drawer/add-mini/index.html
=> Increase button margin

samples/grids/list/overview/index.html, samples/menus/nav-drawer/add-positions-navbar/index.html, samples/scheduling/calendar/disabled-dates/index.html, samples/scheduling/calendar/formatting/index.html, samples/scheduling/calendar/header/index.html, samples/scheduling/calendar/multiple-months/index.html, samples/scheduling/calendar/multiple-selection/index.html, samples/scheduling/calendar/overview/index.html, samples/scheduling/calendar/range-selection/index.html, samples/scheduling/calendar/size/index.html, samples/scheduling/calendar/special-dates/index.html, samples/scheduling/calendar/styling/index.html, samples/scheduling/calendar/styling/webpack.config.js, samples/scheduling/calendar/week-numbers/index.html
=> Add spacing between radio btns and component below and remove div from calendar samples

samples/inputs/radio/styling/src/index.css
=> refactor(radio): update styling sample

samples/editors/date-picker/format/index.html
=> fix date picker format length

samples/editors/multi-column-combobox/overview/package.json, samples/editors/multi-column-combobox/overview/src/index.ts
=> mdd-update-mcc

samples/grids/data-grid/column-filter-expressions/index.html, samples/grids/data-grid/column-filter-expressions/src/index.ts, samples/grids/data-grid/column-filter-operands/.prettierrc, samples/grids/data-grid/column-filter-operands/ReadMe.md, samples/grids/data-grid/column-filter-operands/index.html, samples/grids/data-grid/column-filter-operands/package.json, samples/grids/data-grid/column-filter-operands/sandbox.config.json, samples/grids/data-grid/column-filter-operands/src/DataGridSharedData.ts, samples/grids/data-grid/column-filter-operands/src/index.css, samples/grids/data-grid/column-filter-operands/src/index.ts, samples/grids/data-grid/column-filter-operands/tsconfig.json, samples/grids/data-grid/column-filter-operands/webpack.config.js
added filter operand sample
bug fixing
=> mdd-filter-operands-and-fixes

browser/public/index.html, samples/grids/data-grid/column-filter-operands/src/index.ts
=> mdd-fix-operands

samples/charts/financial-chart/axis-types/index.html, samples/charts/financial-chart/axis-types/src/index.ts
mdd-add-yAxisIsLogarithmic toggle
=> mdd-add-yAxisIsLogarithmic toggle

samples/layouts/dock-manager/overview/package.json, samples/layouts/dock-manager/overview/src/index.ts
=> Update overview sample with documentOnly and allowEmpty features

samples/charts/data-chart/composite-chart/index.html, samples/charts/data-chart/composite-chart/package.json, samples/charts/data-chart/composite-chart/src/index.ts
=> mdd-273880

samples/editors/multi-column-combobox/overview/index.html, samples/editors/multi-column-combobox/overview/src/index.ts
=> mdd-fix-mcc

samples/excel/excel-library/operations-on-worksheets/src/index.ts
=> 273922 - Update index.ts

samples/grids/data-grid/cell-activation/src/index.ts
Disable editing when EditBehavior is not Edit
=> 273921 - Update index.ts

samples/charts/sparkline/markers/index.html
first marker was set from 1 to 10
=> mdd-update-first-marker

samples/charts/category-chart/area-chart-multiple-sources/index.html, samples/charts/category-chart/area-chart-single-source/index.html, samples/charts/category-chart/area-chart-styling/index.html, samples/charts/category-chart/line-chart-multiple-sources/index.html, samples/charts/category-chart/line-chart-single-source/index.html, samples/charts/category-chart/line-chart-styling/index.html, samples/charts/category-chart/line-chart-with-animations/index.html, samples/charts/category-chart/line-chart-with-annotations/index.html, samples/charts/category-chart/marker-options/index.html, samples/charts/category-chart/spline-area-multiple-sources/index.html, samples/charts/category-chart/spline-area-single-source/index.html, samples/charts/category-chart/spline-multiple-sources/index.html, samples/charts/category-chart/spline-single-source/index.html, samples/charts/category-chart/spline-styling/index.html
added plot area margin, from IgEditor
https://github.com/IgniteUI/igniteui-xplat-examples/pull/23
=> mdd-add-plot-area-margin

samples/layouts/expansion-panel/component-customization/index.html, samples/layouts/expansion-panel/component-customization/src/ExpansionPanelCustomization.css, samples/layouts/expansion-panel/properties-and-events/index.html, samples/layouts/expansion-panel/properties-and-events/src/ExpansionPanelPropertiesAndEvents.css, samples/layouts/expansion-panel/properties-and-events/src/index.ts, samples/layouts/expansion-panel/styling/index.html, samples/layouts/expansion-panel/styling/src/ExpansionPanelStyling.css, samples/layouts/expansion-panel/usage/index.html, samples/layouts/expansion-panel/usage/src/ExpansionPanelUsage.css
=> Rename subTitle slot in the Expansion Panel samples

samples/charts/category-chart/high-volume/index.html
=> improve high volume

samples/excel/spreadsheet/activation/package.json, samples/excel/spreadsheet/clipboard/package.json, samples/excel/spreadsheet/commands/package.json, samples/excel/spreadsheet/conditional-formatting/package.json, samples/excel/spreadsheet/config-options/package.json, samples/excel/spreadsheet/filter-dialog/package.json, samples/excel/spreadsheet/format-dialog/package.json, samples/excel/spreadsheet/hyperlinks/package.json, samples/excel/spreadsheet/sort-dialog/package.json
Add missing excel package (Spreadsheet)
=> Add missing excel package (Spreadsheet)

samples/excel/excel-library/operations-on-workbooks/package.json, samples/excel/excel-library/working-with-charts/package.json, samples/excel/excel-library/working-with-sparklines/package.json
=> Add layouts package

samples/grids/tree/basic-example/src/index.ts, samples/layouts/expansion-panel/component-customization/src/index.ts, samples/layouts/expansion-panel/properties-and-events/src/index.ts, samples/layouts/expansion-panel/styling/src/index.ts, samples/layouts/expansion-panel/usage/src/index.ts
Related to https://github.com/IgniteUI/igniteui-webcomponents/issues/420
=> Define icon component in Expansion Panel and Tree samples

package.json, samples/layouts/dock-manager/add-content-runtime/package.json, samples/layouts/dock-manager/customize-buttons/index.html, samples/layouts/dock-manager/customize-buttons/package.json, samples/layouts/dock-manager/embedding-frames/package.json, samples/layouts/dock-manager/hiding-panes/package.json, samples/layouts/dock-manager/overview/package.json, samples/layouts/dock-manager/styling/package.json, samples/layouts/dock-manager/updating-panes/package.json
=> Fix templated icons size

browser/tasks/gulp-samples.js, samples/layouts/stepper/overview/index.html
added backslash back to layouts\stepper sample
removed pivot-grid-remote sample
=> Mdd test wc samples

samples/grids/grid/action-strip/index.html, samples/grids/grid/data-batch-editing-actions/index.html, samples/grids/grid/data-paste-options/index.html, samples/grids/grid/data-validator-service-cross-field/index.html, samples/grids/grid/data-validator-service-extended/index.html, samples/grids/grid/data-validator-service/index.html, samples/grids/grid/multi-row-layout-options/index.html
=> mdd-remove-batchediting

samples/maps/geo-map/display-esri-imagery/src/EsriUtility.ts, samples/maps/geo-map/display-esri-imagery/src/index.ts
=> mdd-update-ocean-imagery-url

samples/grids/grid/filtering-options/index.html, samples/grids/grid/filtering-options/src/index.ts, samples/grids/grid/overview/index.html, samples/grids/grid/overview/src/index.ts, samples/grids/tree-grid/overview/index.html, samples/grids/tree-grid/overview/src/index.ts
mdd-update-excelStyleFiltering
- grid overview, filtering-options
- tree-grid overview
https://github.com/IgniteUI/igniteui-xplat-examples/issues/181
=> mdd-update-excelStyleFiltering

samples/inputs/linear-progress-indicator/dynamic/index.html, samples/inputs/linear-progress-indicator/dynamic/src/index.ts
=> Set non-zero default value

samples/charts/toolbar/actions-built-in-category-chart/package.json, samples/charts/toolbar/actions-built-in-data-chart/package.json, samples/charts/toolbar/layout-actions-for-data-chart/package.json, samples/charts/toolbar/layout-in-vertical-orientation/package.json, samples/charts/toolbar/theming/package.json
=> mdd-update-packages-toolbar

samples/inputs/radio/alignment/index.html, samples/inputs/radio/disabled/index.html, samples/inputs/radio/group/index.html, samples/inputs/radio/label/index.html, samples/inputs/radio/styling/index.html
=> fix(radio-samples): add name attribute

browser/src/router.ts
=> Add a way to prevent scroll in the samples browser

samples/inputs/button-group/overview/src/index.ts, samples/inputs/button-group/selection/index.html, samples/inputs/button-group/selection/src/index.ts, samples/inputs/button-group/size/src/index.css, samples/inputs/button-group/size/src/index.ts
=> fix(button-group): register icons from text and set correct size

samples/gauges/radial-gauge/highlight-needle/index.html
=> mdd-update-highlight-label

samples/grids/grid/state-persistence-main/src/index.ts
Closes [#611](https://github.com/IgniteUI/igniteui-xplat-examples/issues/611) for WC
=> fix(grid-state): await columns loaded to restore state

samples/grids/grid/data-searching/index.html, samples/grids/grid/data-searching/src/index.ts
Closes: #[632](https://github.com/IgniteUI/igniteui-xplat-examples/issues/632)
=> Adding search grid consistency accross all platforms

samples/grids/grid/data-searching/index.html, samples/grids/grid/data-searching/src/index.css, samples/grids/grid/data-searching/src/index.ts, samples/grids/grid/finjs/index.html, samples/grids/grid/finjs/src/index.css, samples/grids/grid/keyboard-navigation-guide/index.html, samples/grids/grid/keyboard-navigation-guide/src/index.css, samples/grids/tree-grid/data-summaries-custom/index.html, samples/grids/tree-grid/data-summaries-custom/src/index.css, samples/grids/tree-grid/finjs/index.html, samples/grids/tree-grid/finjs/src/index.css
Related to https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/32590
=> Remove Display Density setters from custom samples. Use style instead.

samples/grids/grid/custom-context-menu/src/index.ts
Related https://github.com/IgniteUI/igniteui-xplat-examples/issues/710
=> Fix context sample event arg cell id getter changed in new version.

browser/src/router.ts
closes 
https://github.com/IgniteUI/igniteui-angular/issues/14716
=> fix(grid): fixed grid overlay scroll in pop up containers

README.md, tsconfig.json
=> mdd-update-with-dashboards

samples/layouts/tabs/alignment/index.html, samples/layouts/tabs/overview/index.html, samples/layouts/tabs/prefix-suffix/index.html, samples/layouts/tabs/scrolling/src/index.ts
=> Update tabs samples

samples/inputs/tooltip/advanced/package.json, samples/inputs/tooltip/advanced/src/IncomeTaxes.ts, samples/inputs/tooltip/advanced/src/index.ts
Add chart dependencies to the advanced sample.
=> chore(tooltip): add chart dependencies to the advanced sample

samples/inputs/tooltip/advanced/package.json, samples/inputs/tooltip/advanced/src/IncomeTaxes.ts, samples/inputs/tooltip/advanced/src/index.ts
Add chart dependencies to the advanced sample.
=> chore(tooltip): add chart dependencies to the advanced sample (vnext)
